Relax dependency criteria
Before, we were pinning dependencies down to the patch version. This
prevents us from picking up bug fixes. It also (I think) caused failures
like this:

    $ cargo install vmtest
        Updating crates.io index
      Installing vmtest v0.12.0
    error: failed to compile `vmtest v0.12.0`, intermediate artifacts can be found at `/tmp/cargo-installmaJQZ0`

    Caused by:
      failed to select a version for the requirement `clap = "^4.0.26"`
      candidate versions found which didn't match: 3.2.25, 3.2.24, 3.2.23, ...
      location searched: crates.io index
      required by package `vmtest v0.12.0`